# Generated by Django 3.2.8 on 2022-01-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='comapany_name',
            new_name='company_name',
        ),
    ]
